import { StyleSheet } from 'react-native';

export const reservationDetailModalStyles = StyleSheet.create({
  backdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.55)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  backdropTouchLayer: {
    ...StyleSheet.absoluteFillObject,
  },
  card: {
    width: '100%',
    maxWidth: 420,
    borderRadius: 20,
    borderWidth: 1,
    padding: 20,
    maxHeight: '85%',
  },
  contentScroll: {
    marginTop: 6,
  },
  contentScrollContainer: {
    paddingBottom: 8,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 4,
  },
  courtName: {
    fontSize: 18,
    fontWeight: '800',
  },
  courtType: {
    fontSize: 13,
    fontWeight: '500',
  },
  badge: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  badgeText: {
    fontSize: 10,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: 10,
    borderRadius: 10,
    borderWidth: 1,
    marginBottom: 6,
  },
  rowLabel: {
    fontSize: 13,
    flex: 1,
  },
  rowValue: {
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'right',
    flexShrink: 1,
    marginLeft: 8,
  },
  qrWrap: {
    marginTop: 14,
    borderRadius: 14,
    borderWidth: 1,
    paddingVertical: 14,
    paddingHorizontal: 12,
    alignItems: 'center',
    gap: 10,
  },
  qrTitle: {
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  qrCard: {
    borderRadius: 12,
    backgroundColor: '#fff',
    padding: 10,
  },
  qrCodeText: {
    fontSize: 16,
    fontWeight: '800',
    letterSpacing: 1.2,
  },
  cancelBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginTop: 16,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1.5,
  },
  cancelBtnRed: {
    borderColor: '#ef4444',
  },
  refundBtn: {
    borderColor: '#0ea5e9',
    backgroundColor: '#e0f2fe',
  },
  cancelBtnText: {
    color: '#ef4444',
    fontWeight: '700',
    fontSize: 14,
  },
  refundBtnText: {
    color: '#0ea5e9',
  },
  refundBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#dcfce7',
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginBottom: 6,
  },
  refundBannerText: {
    color: '#166534',
    fontSize: 13,
    fontWeight: '600',
    flex: 1,
  },
  confirmBox: {
    marginTop: 16,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: '#ef444440',
    backgroundColor: '#fff5f5',
    padding: 14,
    gap: 6,
  },
  confirmTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#b91c1c',
  },
  confirmBody: {
    fontSize: 13,
    color: '#6b7280',
    marginBottom: 4,
  },
  confirmRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 4,
  },
  confirmNoBtn: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#d1d5db',
    alignItems: 'center',
  },
  confirmNoText: {
    color: '#374151',
    fontWeight: '700',
    fontSize: 13,
  },
  confirmYesBtn: {
    flex: 2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    borderRadius: 10,
    gap: 6,
  },
});
