import { StyleSheet } from 'react-native';

const STRIPE = '#625BF6';

export const mockPaymentSheetStyles = StyleSheet.create({
  overlay: { flex: 1, justifyContent: 'flex-end' },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.45)',
  },
  sheet: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    paddingBottom: 40,
    maxHeight: '92%',
  },
  handle: {
    width: 40,
    height: 4,
    backgroundColor: '#E5E7EB',
    borderRadius: 2,
    alignSelf: 'center',
    marginTop: 12,
    marginBottom: 4,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  cancelBtn: { width: 70 },
  cancelBtnText: { color: STRIPE, fontSize: 15 },
  headerCenter: { alignItems: 'center' },
  merchantName: { fontSize: 13, color: '#6B7280', fontWeight: '500' },
  amountText: { fontSize: 26, fontWeight: '700', color: '#111827', marginTop: 2 },
  body: { paddingHorizontal: 20, paddingTop: 20 },
  sectionLabel: {
    fontSize: 11,
    color: '#6B7280',
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    marginBottom: 8,
  },
  cardGroup: {
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 10,
    overflow: 'hidden',
    backgroundColor: '#fff',
  },
  row: { flexDirection: 'row' },
  halfLeft: {
    flex: 1,
    borderRightWidth: 1,
    borderRightColor: '#E5E7EB',
  },
  halfRight: { flex: 1 },
  borderBottom: { borderBottomWidth: 1, borderBottomColor: '#E5E7EB' },
  inputWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    height: 52,
  },
  input: {
    flex: 1,
    fontSize: 16,
    color: '#111827',
    paddingVertical: 0,
  },
  payBtn: {
    backgroundColor: STRIPE,
    borderRadius: 8,
    paddingVertical: 16,
    alignItems: 'center',
    marginTop: 28,
  },
  payBtnText: { color: '#fff', fontSize: 17, fontWeight: '700' },
  poweredBy: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 16,
    marginBottom: 4,
  },
  poweredByText: { fontSize: 12, color: '#9CA3AF' },
  stripeText: { fontSize: 12, color: '#635BFF', fontWeight: '700' },
});
