import { StyleSheet } from 'react-native';

export const bookingsAdminStyles = StyleSheet.create({
  container: { flex: 1 , paddingTop: 10},
  headerActions: {
    paddingHorizontal: 16,
    flexDirection: 'row',
    gap: 10,
    marginBottom: 15,
  },
  searchBar: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    height: 48,
    borderRadius: 12,
    borderWidth: 1,
  },
  searchInput: { flex: 1, marginLeft: 8, outlineWidth: 0, borderWidth: 0 },
  filtersWrap: {
    paddingHorizontal: 16,
    marginBottom: 14,
    gap: 10,
  },
  filterRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  filterInput: {
    minWidth: 130,
    height: 42,
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 12,
  },
  filterChip: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 999,
    borderWidth: 1,
  },
  clearFiltersBtn: {
    alignSelf: 'flex-start',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  squareBtn: {
    width: 48,
    height: 48,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  gridContent: { paddingHorizontal: 16, gap: 12 },
  gridRow: { gap: 12, justifyContent: 'flex-start', alignItems: 'stretch' },
  cardColumn: { flexGrow: 0, flexShrink: 0, marginBottom: 12, alignSelf: 'stretch' },
  card: {
    flex: 1,
    minHeight: 150,
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 10,
  },
  cardTitle: { fontSize: 18, fontWeight: 'bold' },
  cardSubtitle: { fontSize: 13, opacity: 0.75 },
  rowWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 12 },
  pill: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
  },
  actionsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    borderTopWidth: 1,
    borderTopColor: 'rgba(0,0,0,0.05)',
    paddingTop: 12,
    marginTop: 'auto',
  },
  btnAction: {
    flexGrow: 1,
    minWidth: 120,
    flexDirection: 'row',
    height: 40,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  tableWrap: {
    borderRadius: 16,
    borderWidth: 1,
    overflow: 'hidden',
    marginHorizontal: 16,
  },
  tableHeader: {
    flexDirection: 'row',
    paddingVertical: 12,
    paddingHorizontal: 12,
    columnGap: 10,
    borderBottomWidth: 1,
  },
  tableRow: {
    flexDirection: 'row',
    paddingVertical: 12,
    paddingHorizontal: 12,
    columnGap: 10,
    borderBottomWidth: 1,
    alignItems: 'center',
  },
  colId: { flex: 0.7 },
  colUser: { flex: 1.2, minWidth: 0, flexShrink: 1 },
  colCourt: { flex: 1.1 },
  colDate: { flex: 1.1 },
  colStatus: { flex: 1, minWidth: 94, paddingRight: 6 },
  colActions: { flex: 0.9, minWidth: 84, alignItems: 'flex-end' },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    maxHeight: '92%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalTitle: { fontSize: 22, fontWeight: 'bold' },
  input: { borderWidth: 1, borderRadius: 12, padding: 12, marginBottom: 14 },
  helperText: {
    fontSize: 12,
    marginTop: -6,
    marginBottom: 12,
  },
  selectButton: {
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  selectButtonText: {
    fontSize: 15,
    fontWeight: '700',
    flex: 1,
    marginRight: 12,
  },
  dropdownBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.35)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 12,
  },
  dropdownCard: {
    width: '100%',
    maxWidth: 420,
    borderRadius: 16,
    borderWidth: 1,
    padding: 14,
    maxHeight: 420,
  },
  dropdownTitle: {
    fontSize: 16,
    fontWeight: '800',
    marginBottom: 10,
  },
  dropdownList: {
    maxHeight: 320,
  },
  dropdownOption: {
    borderWidth: 1,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginBottom: 8,
  },
  dropdownOptionSelected: {
    borderWidth: 1,
  },
  dropdownOptionText: {
    fontSize: 14,
    fontWeight: '700',
  },
  dropdownOptionTextSelected: {
    fontSize: 14,
    fontWeight: '800',
  },
  twoColumnsRow: { flexDirection: 'row', gap: 10 },
  column: { flex: 1 },
  saveBtn: {
    height: 50,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 12,
  },
  saveBtnText: { color: 'white', fontSize: 16, fontWeight: 'bold' },
  segmentedRow: { flexDirection: 'row', gap: 8, marginBottom: 14, flexWrap: 'wrap' },
  segment: {
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 999,
    borderWidth: 1,
  },
});
