import { StyleSheet } from 'react-native';

export const pistasStyles = StyleSheet.create({
  container: { flex: 1, paddingTop: 10 },
  headerActions: {
    paddingHorizontal: 16,
    flexDirection: 'row',
    gap: 10,
    marginBottom: 15,
  },
  searchBar: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    height: 48,
    borderRadius: 12,
    borderWidth: 1,
  },
  searchInput: { flex: 1, marginLeft: 8, outlineWidth: 0, borderWidth: 0 },
  addBtn: {
    width: 48,
    height: 48,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  squareBtn: {
    width: 48,
    height: 48,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  listContent: { paddingHorizontal: 16 },
  gridContent: { paddingHorizontal: 16, gap: 12 },
  gridRow: { gap: 12, justifyContent: 'flex-start' },
  cardColumn: { flexGrow: 0, flexShrink: 0, alignSelf: 'stretch' },
  card: { borderRadius: 18, padding: 16, marginBottom: 12, borderWidth: 1 },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  cardTitle: { fontSize: 18, fontWeight: 'bold' },
  cardSubtitle: { fontSize: 13, opacity: 0.6 },
  statusBadge: { paddingHorizontal: 10, paddingVertical: 10, borderRadius: 8, alignSelf: 'flex-start' },
  cardDetails: { flexDirection: 'row', gap: 15, marginBottom: 15 },
  actionsRow: {
    flexDirection: 'row',
    gap: 10,
    borderTopWidth: 1,
    borderTopColor: 'rgba(0,0,0,0.05)',
    paddingTop: 12,
  },
  btnAction: {
    flex: 1,
    flexDirection: 'row',
    height: 40,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  // Modal form
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    height: '90%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalTitle: { fontSize: 22, fontWeight: 'bold' },
  input: { borderWidth: 1, borderRadius: 12, padding: 12, marginBottom: 14 },
  readOnlyField: {
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    marginBottom: 14,
    fontWeight: '600',
  },
  switchRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  saveBtn: {
    height: 50,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
  },
  saveBtnText: { color: 'white', fontSize: 16, fontWeight: 'bold' },
  // Weekly schedule grid
  weeklyGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 14,
  },
  weeklyRow: {
    borderWidth: 1,
    borderRadius: 14,
    padding: 12,
  },
  weeklyDayLabel: {
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 10,
  },
  weeklyHoursRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  weeklyHourInput: {
    flex: 1,
    borderWidth: 1,
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  weeklyClosedRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 12,
  },
  tableWrap: {
    borderRadius: 16,
    borderWidth: 1,
    overflow: 'hidden',
    marginHorizontal: 16,
  },
  tableHeader: {
    flexDirection: 'row',
    paddingVertical: 12,
    paddingHorizontal: 12,
    columnGap: 10,
    borderBottomWidth: 1,
  },
  tableRow: {
    flexDirection: 'row',
    paddingVertical: 12,
    paddingHorizontal: 12,
    columnGap: 10,
    borderBottomWidth: 1,
    alignItems: 'center',
  },
  colName: { flex: 1.4, minWidth: 0, flexShrink: 1 },
  colType: { flex: 1, minWidth: 0, flexShrink: 1 },
  colImage: { flex: 0.9, minWidth: 88, alignItems: 'center' },
  colPrice: { flex: 0.8, minWidth: 86 },
  colStatus: { flex: 1, minWidth: 100 },
  colActions: { flex: 1, minWidth: 92, alignItems: 'flex-end' },
});
