import { StyleSheet } from 'react-native';

export const membershipsStyles = StyleSheet.create({
  container: { flex: 1 , paddingTop: 10},
  headerActions: {
    paddingHorizontal: 16,
    flexDirection: 'row',
    gap: 10,
    marginBottom: 15,
  },
  searchBar: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    height: 48,
    borderRadius: 12,
    borderWidth: 1,
  },
  searchInput: { flex: 1, marginLeft: 8, outlineWidth: 0, borderWidth: 0 },
  addBtn: {
    width: 48,
    height: 48,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  squareBtn: {
    width: 48,
    height: 48,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  listContent: { paddingHorizontal: 16 },
  gridContent: { paddingHorizontal: 16, gap: 12 },
  gridRow: { gap: 12, justifyContent: 'flex-start' },
  cardColumn: { flexGrow: 0, flexShrink: 0, alignSelf: 'stretch' },
  card: { borderRadius: 18, padding: 16, marginBottom: 12, borderWidth: 1 },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  cardTitle: { fontSize: 18, fontWeight: 'bold' },
  cardSubtitle: { fontSize: 13, opacity: 0.75 },
  badge: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    alignSelf: 'flex-start',
  },
  actionsRow: {
    flexDirection: 'row',
    gap: 10,
    borderTopWidth: 1,
    borderTopColor: 'rgba(0,0,0,0.05)',
    paddingTop: 12,
  },
  btnAction: {
    flex: 1,
    flexDirection: 'row',
    height: 40,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalTitle: { fontSize: 22, fontWeight: 'bold' },
  input: { borderWidth: 1, borderRadius: 12, padding: 12, marginBottom: 14 },
  saveBtn: {
    height: 50,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
  },
  saveBtnText: { color: 'white', fontSize: 16, fontWeight: 'bold' },
  multilineInput: {
    minHeight: 90,
    textAlignVertical: 'top',
  },
  tableWrap: {
    borderRadius: 16,
    borderWidth: 1,
    overflow: 'hidden',
    marginHorizontal: 16,
  },
  tableHeader: {
    flexDirection: 'row',
    paddingVertical: 12,
    paddingHorizontal: 12,
    columnGap: 10,
    borderBottomWidth: 1,
  },
  tableRow: {
    flexDirection: 'row',
    paddingVertical: 12,
    paddingHorizontal: 12,
    columnGap: 10,
    borderBottomWidth: 1,
    alignItems: 'center',
  },
  colType: { flex: 1.2, minWidth: 0, flexShrink: 1 },
  colRange: { flex: 0.8, minWidth: 60 },
  colDiscount: { flex: 0.8, minWidth: 60 },
  colBookings: { flex: 1, minWidth: 0, flexShrink: 1 },
  colActions: { flex: 0.8, minWidth: 74, alignItems: 'flex-end' },
});
