import { StyleSheet } from 'react-native';

export const reviewsStyles = StyleSheet.create({
  container: { flex: 1, paddingTop: 10 },
  headerActions: {
    paddingHorizontal: 16,
    flexDirection: 'row',
    gap: 10,
    marginBottom: 15,
  },
  searchBar: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    height: 48,
    borderRadius: 12,
    borderWidth: 1,
  },
  searchInput: { flex: 1, marginLeft: 8 },
  filtersSection: {
    paddingHorizontal: 16,
    marginBottom: 12,
  },
  filtersLabel: {
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 6,
  },
  filterChip: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginRight: 8,
    marginBottom: 10,
  },
  addBtn: {
    width: 48,
    height: 48,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  squareBtn: {
    width: 48,
    height: 48,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  listContent: { paddingHorizontal: 16 },
  gridContent: { paddingHorizontal: 16, gap: 12 },
  gridRow: { justifyContent: 'flex-start' },
  cardColumn: { padding: 6,alignSelf: 'stretch' },
  card: {
    flex: 1,
    borderRadius: 18,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 10,
    gap: 10,
  },
  cardTitle: { fontSize: 18, fontWeight: 'bold' },
  cardSubtitle: { fontSize: 13, opacity: 0.78 },
  metaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 10,
  },
  badge: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    alignSelf: 'flex-start',
    borderWidth: 1,
  },
  reviewText: {
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 12,
  },
  adminAnswerBox: {
    borderWidth: 1,
    borderRadius: 12,
    padding: 10,
    marginBottom: 12,
  },
  adminAnswerLabel: {
    fontSize: 11,
    fontWeight: '700',
    marginBottom: 4,
    textTransform: 'uppercase',
  },
  adminAnswerText: {
    fontSize: 13,
    lineHeight: 18,
  },
  actionsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    borderTopWidth: 1,
    borderTopColor: 'rgba(0,0,0,0.05)',
    paddingTop: 12,
  },
  btnAction: {
    minWidth: 110,
    flexDirection: 'row',
    height: 40,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 12,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    maxHeight: '92%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalTitle: { fontSize: 22, fontWeight: 'bold' },
  input: { borderWidth: 1, borderRadius: 12, padding: 12, marginBottom: 14 },
  reviewInfoCard: {
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    marginBottom: 14,
  },
  reviewInfoTitle: {
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 4,
  },
  reviewInfoMeta: {
    fontSize: 12,
    marginBottom: 8,
  },
  reviewInfoBody: {
    fontSize: 14,
    lineHeight: 20,
  },
  multilineInput: {
    minHeight: 110,
    textAlignVertical: 'top',
  },
  saveBtn: {
    height: 50,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
  },
  saveBtnText: { color: 'white', fontSize: 16, fontWeight: 'bold' },
  selectButton: {
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  selectButtonText: {
    flex: 1,
    marginRight: 12,
    fontSize: 14,
    fontWeight: '500',
  },
  dropdownBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.35)',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  dropdownCard: {
    borderRadius: 16,
    borderWidth: 1,
    padding: 18,
    maxHeight: '70%',
  },
  dropdownTitle: {
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 14,
  },
  dropdownList: {
    maxHeight: 320,
  },
  dropdownOption: {
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 12,
    marginBottom: 10,
  },
  dropdownOptionSelected: {
    borderWidth: 1.5,
  },
  dropdownOptionText: {
    fontSize: 14,
    fontWeight: '500',
  },
  dropdownOptionTextSelected: {
    fontSize: 14,
    fontWeight: '700',
  },
  tableWrap: {
    borderRadius: 16,
    borderWidth: 1,
    overflow: 'hidden',
    marginHorizontal: 16,
  },
  tableHeader: {
    flexDirection: 'row',
    paddingVertical: 12,
    paddingHorizontal: 12,
    columnGap: 10,
    borderBottomWidth: 1,
    alignItems: 'center',
  },
  tableRow: {
    flexDirection: 'row',
    paddingVertical: 12,
    paddingHorizontal: 12,
    columnGap: 10,
    borderBottomWidth: 1,
    alignItems: 'center',
  },
  colCourt: { flex: 1.2, minWidth: 120, flexShrink: 1 },
  colUser: { flex: 1.1, minWidth: 120, flexShrink: 1 },
  colTitle: { flex: 1.4, minWidth: 160, flexShrink: 1 },
  colRating: { flex: 0.8, minWidth: 70 },
  colVisibility: { flex: 0.9, minWidth: 86 },
  colActions: { flex: 1, minWidth: 140, alignItems: 'flex-end' },
});
