import { StyleSheet } from 'react-native';

export const resetPasswordStyles = StyleSheet.create({
  screen: {
    flex: 1,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  glow: {
    position: 'absolute',
    width: 280,
    height: 280,
    borderRadius: 140,
    top: '20%',
    opacity: 0.9,
  },
  card: {
    width: '100%',
    maxWidth: 360,
    borderRadius: 30,
    paddingVertical: 28,
    paddingHorizontal: 22,
    borderWidth: 0.8,
    overflow: 'hidden',
    alignItems: 'center',
  },
  title: {
    fontSize: 28,
    fontWeight: '700',
    textAlign: 'center',
    marginTop: 6,
    marginBottom: 14,
  },
  message: {
    fontSize: 14,
    fontWeight: '500',
    lineHeight: 20,
    textAlign: 'center',
    marginBottom: 16,
  },
  loaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 8,
    marginBottom: 12,
  },
  loaderText: {
    fontSize: 14,
    fontWeight: '500',
  },
  feedback: {
    width: '100%',
    textAlign: 'center',
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 18,
    marginTop: 10,
    marginBottom: 8,
  },
  actionButton: {
    width: '100%',
    marginTop: 16,
  },
  backButton: {
    width: '100%',
    marginTop: 10,
  },
});

export const forgotPasswordStyles = StyleSheet.create({
  screen: {
    flex: 1,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  glow: {
    position: 'absolute',
    width: 280,
    height: 280,
    borderRadius: 140,
    top: '20%',
    opacity: 0.9,
  },
  card: {
    width: '100%',
    maxWidth: 360,
    borderRadius: 30,
    paddingVertical: 28,
    paddingHorizontal: 22,
    borderWidth: 0.8,
    overflow: 'hidden',
    alignItems: 'center',
  },
  title: {
    fontSize: 28,
    fontWeight: '700',
    textAlign: 'center',
    marginTop: 6,
    marginBottom: 14,
  },
  message: {
    fontSize: 14,
    fontWeight: '500',
    lineHeight: 20,
    textAlign: 'center',
    marginBottom: 16,
  },
  loaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 8,
    marginBottom: 12,
  },
  loaderText: {
    fontSize: 14,
    fontWeight: '500',
  },
  feedback: {
    width: '100%',
    textAlign: 'center',
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 18,
    marginTop: 10,
    marginBottom: 8,
  },
  actionButton: {
    width: '100%',
    marginTop: 16,
  },
  backButton: {
    width: '100%',
    marginTop: 10,
  },
});

export const verifyEmailStyles = StyleSheet.create({
  screen: {
    flex: 1,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  glow: {
    position: 'absolute',
    width: 280,
    height: 280,
    borderRadius: 140,
    top: '20%',
    opacity: 0.9,
  },
  card: {
    width: '100%',
    maxWidth: 360,
    borderRadius: 30,
    paddingVertical: 28,
    paddingHorizontal: 22,
    borderWidth: 0.8,
    overflow: 'hidden',
    alignItems: 'center',
  },
  title: {
    fontSize: 28,
    fontWeight: '700',
    textAlign: 'center',
    marginTop: 6,
  },
  subtitle: {
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
    marginTop: 2,
    marginBottom: 16,
  },
  centeredBlock: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    minHeight: 120,
    marginBottom: 10,
  },
  statusBadge: {
    fontSize: 17,
    fontWeight: '700',
    textAlign: 'center',
  },
  message: {
    fontSize: 15,
    textAlign: 'center',
    lineHeight: 22,
  },
  actionButton: {
    width: '100%',
    marginTop: 10,
  },
});

export const confirmEmailStyles = StyleSheet.create({
  screen: {
    flex: 1,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  glow: {
    position: 'absolute',
    width: 280,
    height: 280,
    borderRadius: 140,
    top: '20%',
    opacity: 0.9,
  },
  card: {
    width: '100%',
    maxWidth: 360,
    borderRadius: 30,
    paddingVertical: 28,
    paddingHorizontal: 22,
    borderWidth: 0.8,
    overflow: 'hidden',
    alignItems: 'center',
  },
  title: {
    fontSize: 28,
    fontWeight: '700',
    textAlign: 'center',
    marginTop: 6,
    marginBottom: 14,
  },
  message: {
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 24,
    textAlign: 'center',
    marginBottom: 10,
  },
  emailText: {
    fontWeight: '700',
  },
  loaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 8,
    marginBottom: 4,
  },
  loaderText: {
    fontSize: 14,
    fontWeight: '500',
  },
  feedback: {
    width: '100%',
    textAlign: 'center',
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 20,
    marginTop: 6,
  },
  actionButton: {
    width: '100%',
    marginTop: 12,
  },
});

export const easterEggPepStyles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  confetti: {
    position: 'absolute',
    top: -20,
  },
  floatingBall: {
    position: 'absolute',
  },
  glassCard: {
    padding: 25,
    borderRadius: 30,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.6)',
    alignItems: 'center',
    overflow: 'hidden',
  },
  photoFrame: {
    width: 150,
    height: 150,
    borderRadius: 75,
    borderWidth: 6,
    borderColor: '#95ADEE',
    overflow: 'hidden',
    backgroundColor: '#ddd',
    marginBottom: 20,
  },
  profeImage: {
    width: '100%',
    height: '100%',
  },
  congrats: {
    fontSize: 26,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 10,
  },
  phraseWrapper: {
    height: 110,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  innerPhrase: {
    alignItems: 'center',
  },
  jokeText: {
    fontSize: 19,
    textAlign: 'center',
    color: '#444',
    lineHeight: 26,
    fontWeight: '500',
    fontStyle: 'italic',
  },
  signature: {
    marginTop: 20,
    fontSize: 14,
    color: '#95ADEE',
    fontWeight: 'bold',
  },
});

export const authLayoutStyles = StyleSheet.create({
  background: { flex: 1 },
  container: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  controlsWrap: {
    position: 'absolute',
    top: 50,
    right: 16,
    width: 170,
    borderRadius: 16,
    borderWidth: 0.8,
    padding: 8,
    gap: 8,
    overflow: 'hidden',
  },
  controlsWrapCompact: {
    width: 64,
    alignItems: 'center',
  },
  controlsWrapSmallWeb: {
    top: 12,
    right: 12,
    flexDirection: 'row',
    width: 110,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    padding: 4,
  },
  controlsWrapLargeWeb: {
    width: 230,
    padding: 10,
    gap: 10,
  },
  controlButtonSmallWeb: {
    width: 44,
    height: 44,
    minHeight: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    paddingRight: 0,
  },
  controlButton: {
    width: '100%',
    minHeight: 42,
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    paddingRight: 8,
  },
  controlButtonCompact: {
    width: 48,
    height: 48,
    minHeight: 48,
    borderRadius: 24,
    justifyContent: 'center',
    paddingRight: 0,
  },
  controlIcon: {
    margin: 0,
  },
  controlText: {
    fontSize: 12,
    fontWeight: '700',
    flexShrink: 1,
  },
});
