import { StyleSheet } from 'react-native';
import { AppTheme } from '../theme';

const createPistasTabStyles = (theme: AppTheme) =>
  StyleSheet.create({
    pageContainer: {
      backgroundColor: theme.background,
    },
    heroCard: {
      borderRadius: 24,
      padding: 20,
      marginTop: 8,
      marginBottom: 20,
      backgroundColor: theme.primarySoft,
      borderWidth: 1,
      borderColor: theme.borderAccentSoft,
    },
    heroTag: {
      alignSelf: 'flex-start',
      backgroundColor: theme.primarySoft,
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 999,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: theme.borderAccentSoft,
    },
    heroTagText: {
      color: theme.primary,
      fontWeight: '800',
      fontSize: 12,
      letterSpacing: 0.6,
      textTransform: 'uppercase',
    },
    heroTitle: {
      fontSize: 28,
      lineHeight: 34,
      fontWeight: '900',
      color: theme.textTitle,
    },
    heroSubtitle: {
      marginTop: 10,
      fontSize: 15,
      lineHeight: 22,
      color: theme.textSubtitle,
    },
    heroActionsRow: {
      marginTop: 12,
      flexDirection: 'row',
      gap: 8,
      flexWrap: 'wrap',
    },
    filterBadge: {
      alignSelf: 'flex-start',
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      borderWidth: 1,
      borderColor: theme.borderAccentSoft,
      backgroundColor: theme.surface,
      borderRadius: 999,
      paddingVertical: 8,
      paddingHorizontal: 10,
    },
    filterBadgeText: {
      color: theme.primary,
      fontSize: 12,
      fontWeight: '800',
    },
    dateChipsRow: {
      marginBottom: 10,
    },
    dateChip: {
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: theme.borderSoft,
      marginRight: 8,
      backgroundColor: theme.surface,
    },
    dateChipActive: {
      borderColor: theme.primary,
      backgroundColor: theme.primary,
    },
    dateChipText: {
      color: theme.textBody,
      fontSize: 12,
      fontWeight: '700',
      textTransform: 'capitalize',
    },
    dateChipTextActive: {
      color: theme.onPrimary,
    },
    feedbackText: {
      color: theme.textBody,
      fontSize: 14,
      lineHeight: 20,
      marginTop: 4,
      marginBottom: 12,
    },
    sectionHeader: {
      marginBottom: 14,
    },
    sectionTitle: {
      fontSize: 22,
      fontWeight: '900',
      color: theme.textTitle,
    },
    sectionSubtitle: {
      marginTop: 4,
      color: theme.textSubtitle,
      fontSize: 13,
      fontWeight: '500',
    },
    gridContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 16,
      justifyContent: 'flex-start',
      alignItems: 'stretch',
    },
    catalogCard: {
      minHeight: 210,
      borderRadius: 18,
      overflow: 'hidden',
      backgroundColor: theme.cardBackground,
      borderWidth: 1,
      borderColor: theme.borderAccentSoft,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.15,
      shadowRadius: 14,
      elevation: 5,
    },
    catalogCardBg: {
      flex: 1,
    },
    catalogCardOverlay: {
      flex: 1,
      justifyContent: 'space-between',
      padding: 18,
    },
    catalogHeaderRow: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
    },
    statusBadge: {
      backgroundColor: 'rgba(255,255,255,0.2)',
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 999,
    },
    statusText: {
      color: '#FFFFFF',
      fontSize: 11,
      fontWeight: '800',
      letterSpacing: 0.5,
      textTransform: 'uppercase',
    },
    catalogBottom: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-end',
    },
    catalogTitle: {
      color: '#FFFFFF',
      fontSize: 22,
      fontWeight: '900',
      textShadowColor: 'rgba(0,0,0,0.45)',
      textShadowOffset: { width: 0, height: 1 },
      textShadowRadius: 8,
    },
    catalogMeta: {
      marginTop: 6,
      color: 'rgba(255,255,255,0.84)',
      fontSize: 13,
      fontWeight: '500',
      maxWidth: 190,
    },
    pricePill: {
      backgroundColor: 'rgba(255,255,255,0.92)',
      borderRadius: 999,
      paddingHorizontal: 12,
      paddingVertical: 7,
    },
    pricePillText: {
      color: theme.primary,
      fontSize: 12,
      fontWeight: '900',
    },
    catalogFooter: {
      marginTop: 12,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    catalogCta: {
      color: '#FFFFFF',
      fontSize: 13,
      fontWeight: '800',
      letterSpacing: 0.2,
    },
    sportCard: {
      borderRadius: 18,
      borderWidth: 1,
      borderColor: theme.borderAccentSoft,
      backgroundColor: theme.surface,
      gap: 0,
      overflow: 'hidden',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.12,
      shadowRadius: 14,
      elevation: 5,
      minHeight: 242,
    },
    sportCardImage: {
      minHeight: 184,
      justifyContent: 'flex-end',
    },
    sportCardImageStyle: {
      borderTopLeftRadius: 18,
      borderTopRightRadius: 18,
    },
    sportCardOverlay: {
      flex: 1,
      padding: 14,
      justifyContent: 'space-between',
    },
    sportCardHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 8,
    },
    sportCardTitle: {
      color: '#FFFFFF',
      fontSize: 20,
      fontWeight: '900',
      textShadowColor: 'rgba(0,0,0,0.45)',
      textShadowOffset: { width: 0, height: 1 },
      textShadowRadius: 8,
    },
    sportCardDescription: {
      color: 'rgba(255,255,255,0.88)',
      fontSize: 13,
      lineHeight: 18,
      marginTop: 8,
      fontWeight: '500',
    },
    sportChipsWrap: {
      marginTop: 10,
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    sportChip: {
      borderRadius: 999,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.32)',
      backgroundColor: 'rgba(255,255,255,0.14)',
      paddingHorizontal: 10,
      paddingVertical: 6,
    },
    sportChipText: {
      color: '#FFFFFF',
      fontSize: 12,
      fontWeight: '700',
    },
    reserveButton: {
      borderTopWidth: 1,
      borderTopColor: theme.borderSoft,
      paddingVertical: 16,
      paddingHorizontal: 20,
      width: '100%',
      alignItems: 'center',
      justifyContent: 'center',
    },
    reserveButtonText: {
      fontSize: 14,
      fontWeight: '900',
      letterSpacing: 0.2,
    },
  });

export default createPistasTabStyles;
