import { StyleSheet } from 'react-native';
import { AppTheme } from '../theme';

export const createCreateBookingStyles = (theme: AppTheme) =>
  StyleSheet.create({
    screen: {
      flex: 1,
      backgroundColor: theme.background,
    },
    scrollContent: {
      paddingHorizontal: 12,
      paddingBottom: 100,
    },
    formCard: {
      borderRadius: 18,
      backgroundColor: theme.surface,
      borderWidth: 1,
      borderColor: theme.borderSoft,
      padding: 16,
    },
    badgeRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderRadius: 14,
      backgroundColor: theme.primarySoft,
      marginBottom: 8,
    },
    badgeText: {
      color: theme.textPrimary,
      fontWeight: '700',
      fontSize: 13,
    },
    label: {
      marginTop: 12,
      marginBottom: 6,
      color: theme.textPrimary,
      fontWeight: '700',
    },
    readonlyField: {
      borderWidth: 1,
      borderColor: theme.borderInput,
      backgroundColor: theme.inputBgSoft,
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 11,
    },
    readonlyValue: {
      color: theme.textTitle,
      fontSize: 15,
      fontWeight: '700',
    },
    chipsRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
    },
    selectButton: {
      borderWidth: 1,
      borderColor: theme.borderInput,
      borderRadius: 10,
      backgroundColor: theme.inputBgSoft,
      paddingHorizontal: 12,
      paddingVertical: 12,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    selectButtonText: {
      color: theme.textTitle,
      fontSize: 15,
      fontWeight: '700',
    },
    dropdownBackdrop: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.3)',
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 12,
    },
    dropdownCard: {
      width: '100%',
      maxWidth: 360,
      backgroundColor: theme.surface,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.borderSoft,
      padding: 12,
      maxHeight: 360,
    },
    dropdownTitle: {
      color: theme.textTitle,
      fontSize: 14,
      fontWeight: '800',
      marginBottom: 10,
    },
    dropdownList: {
      maxHeight: 280,
    },
    dropdownOption: {
      borderWidth: 1,
      borderColor: theme.borderInput,
      borderRadius: 10,
      paddingVertical: 10,
      paddingHorizontal: 12,
      marginBottom: 8,
      backgroundColor: theme.surface,
    },
    dropdownOptionSelected: {
      borderColor: theme.primary,
      backgroundColor: theme.primarySoft,
    },
    dropdownOptionText: {
      color: theme.textPrimary,
      fontSize: 14,
      fontWeight: '700',
    },
    dropdownOptionTextSelected: {
      color: theme.textTitle,
      fontSize: 14,
      fontWeight: '800',
    },
    chip: {
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: theme.borderInput,
      backgroundColor: theme.surface,
      minWidth: 74,
      alignItems: 'center',
      justifyContent: 'center',
    },
    chipSelected: {
      backgroundColor: theme.primary,
      borderColor: theme.primary,
    },
    chipText: {
      color: theme.textPrimary,
      fontWeight: '700',
      fontSize: 14,
    },
    chipTextSelected: {
      color: theme.onPrimary,
      fontWeight: '800',
      fontSize: 14,
    },
    chipDisabled: {
      opacity: 0.35,
      backgroundColor: theme.backgroundAlt,
      borderColor: theme.borderSoft,
    },
    chipTextDisabled: {
      color: theme.textMuted,
      fontWeight: '600',
      fontSize: 14,
    },
    noteInput: {
      borderWidth: 1,
      borderColor: theme.borderInput,
      borderRadius: 10,
      backgroundColor: theme.inputBgSoft,
      color: theme.textPrimary,
      paddingHorizontal: 12,
      paddingVertical: 10,
      minHeight: 90,
    },
    emptySlotsCard: {
      borderWidth: 1,
      borderColor: theme.borderSoft,
      backgroundColor: theme.backgroundAlt,
      borderRadius: 12,
      padding: 12,
    },
    emptySlotsTitle: {
      color: theme.textTitle,
      fontWeight: '800',
      fontSize: 14,
    },
    emptySlotsText: {
      marginTop: 4,
      color: theme.textMuted,
      fontSize: 12,
    },
    totalCard: {
      marginTop: 14,
      borderWidth: 1,
      borderColor: theme.borderSoft,
      backgroundColor: theme.backgroundAlt,
      borderRadius: 12,
      padding: 12,
      gap: 4,
    },
    totalLabel: {
      color: theme.textMuted,
      fontSize: 12,
      textTransform: 'uppercase',
      fontWeight: '700',
    },
    totalValue: {
      color: theme.textTitle,
      fontSize: 22,
      fontWeight: '900',
    },
    totalMeta: {
      color: theme.textMuted,
      fontSize: 12,
      fontWeight: '600',
    },
    submit: {
      marginTop: 16,
      borderRadius: 12,
      backgroundColor: theme.primary,
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 14,
    },
    submitDisabled: {
      opacity: 0.7,
    },
    submitText: {
      color: theme.onPrimary,
      fontWeight: '800',
      fontSize: 15,
    },
  });
