import { StyleSheet } from 'react-native';
import { AppTheme } from '../theme';

export const createCreateBookingStyles = (theme: AppTheme) =>
  StyleSheet.create({
    loadingRoot: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    scrollContent: {
      paddingHorizontal: 16,
      paddingBottom: 40,
      backgroundColor: theme.background,
    },
    heroCard: {
      height: 220,
      borderRadius: 20,
      overflow: 'hidden',
      marginTop: 8,
      marginBottom: 12,
    },
    heroImage: {
      flex: 1,
    },
    heroImageRadius: {
      borderRadius: 20,
    },
    heroOverlay: {
      flex: 1,
      padding: 18,
      justifyContent: 'space-between',
    },
    heroTopRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    heroChip: {
      alignSelf: 'flex-start',
      backgroundColor: 'rgba(255,255,255,0.16)',
      borderRadius: 999,
      paddingHorizontal: 12,
      paddingVertical: 6,
    },
    heroChipText: {
      color: theme.onPrimary,
      fontSize: 11,
      fontWeight: '800',
      letterSpacing: 0.6,
      textTransform: 'uppercase',
    },
    backButton: {
      backgroundColor: 'rgba(0,0,0,0.24)',
      borderRadius: 999,
      width: 36,
      height: 36,
      alignItems: 'center',
      justifyContent: 'center',
    },
    heroTitle: {
      color: theme.onPrimary,
      fontSize: 28,
      lineHeight: 32,
      fontWeight: '900',
      textShadowColor: 'rgba(0,0,0,0.45)',
      textShadowOffset: { width: 0, height: 1 },
      textShadowRadius: 6,
    },
    heroSubtitle: {
      marginTop: 6,
      color: theme.onPrimary,
      fontSize: 16,
      fontWeight: '700',
      opacity: 0.95,
    },
    formCard: {
      padding: 16,
      borderRadius: 18,
      backgroundColor: theme.surface,
      borderWidth: 1,
      borderColor: theme.borderSoft,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.06,
      shadowRadius: 12,
      elevation: 3,
    },
    badgeRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderRadius: 14,
      backgroundColor: theme.primarySoft,
      marginBottom: 8,
    },
    badgeText: {
      color: theme.textPrimary,
      fontWeight: '700',
    },
    label: {
      marginTop: 12,
      marginBottom: 6,
      fontWeight: '700',
      color: theme.textPrimary,
    },
    input: {
      borderWidth: 1,
      borderColor: theme.borderInput,
      padding: 12,
      borderRadius: 10,
      backgroundColor: theme.inputBgSoft,
      color: theme.textPrimary,
    },
    multilineInput: {
      minHeight: 96,
      paddingTop: 12,
    },
    infoRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingVertical: 4,
    },
    infoValueText: {
      flex: 1,
      color: theme.textSecondary,
      fontSize: 14,
      fontWeight: '500',
    },
    selectorButton: {
      borderWidth: 1,
      borderColor: theme.borderInput,
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 12,
      backgroundColor: theme.inputBgSoft,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    selectorContent: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      flex: 1,
    },
    selectorCourtText: {
      flex: 1,
      color: theme.textTitle,
      fontSize: 16,
      fontWeight: '800',
    },
    selectorHintText: {
      marginTop: 3,
      color: theme.textMuted,
      fontSize: 11,
      fontWeight: '400',
    },
    dateRow: {
      flexDirection: 'row',
      gap: 10,
    },
    dateBtn: {
      padding: 12,
      borderWidth: 1,
      borderColor: theme.borderInput,
      borderRadius: 10,
      backgroundColor: theme.surface,
    },
    dateBtnLarge: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    dateBtnText: {
      color: theme.textPrimary,
      fontWeight: '600',
    },
    durationHeader: {
      marginTop: 12,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    linkText: {
      color: theme.primary,
      fontWeight: '800',
    },
    summaryRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: 8,
      gap: 12,
    },
    summaryText: {
      color: theme.textPrimary,
      fontSize: 15,
    },
    summaryStrong: {
      fontWeight: '800',
    },
    chipsRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      marginTop: 10,
      gap: 10,
    },
    chip: {
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 20,
      backgroundColor: theme.surface,
      borderWidth: 1,
      borderColor: theme.borderInput,
      minWidth: 84,
      alignItems: 'center',
      justifyContent: 'center',
    },
    chipSelected: {
      backgroundColor: theme.primary,
      borderColor: theme.primary,
    },
    chipText: {
      color: theme.textPrimary,
      fontWeight: '700',
      fontSize: 14,
    },
    chipTextSelected: {
      color: theme.onPrimary,
      fontWeight: '800',
      fontSize: 14,
    },
    stepperRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 12,
      gap: 10,
    },
    stepperBtn: {
      width: 44,
      height: 36,
      borderRadius: 8,
      backgroundColor: theme.backgroundAlt,
      alignItems: 'center',
      justifyContent: 'center',
    },
    stepperText: {
      fontSize: 18,
      fontWeight: '800',
      color: theme.textPrimary,
    },
    stepperCenter: {
      flex: 1,
      alignItems: 'center',
    },
    stepperValue: {
      fontWeight: '800',
      fontSize: 16,
      color: theme.textPrimary,
    },
    totalCard: {
      marginTop: 16,
      padding: 16,
      borderRadius: 16,
      backgroundColor: theme.backgroundAlt,
      borderWidth: 1,
      borderColor: theme.borderSoft,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    totalLabel: {
      color: theme.textMuted,
      fontSize: 12,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 0.6,
    },
    totalValue: {
      color: theme.textPrimary,
      fontSize: 24,
      fontWeight: '900',
      marginTop: 4,
    },
    totalMeta: {
      alignItems: 'flex-end',
      gap: 4,
    },
    totalMetaText: {
      color: theme.textMuted,
      fontSize: 12,
      fontWeight: '600',
    },
    submit: {
      marginTop: 18,
      backgroundColor: theme.primary,
      padding: 14,
      borderRadius: 12,
      alignItems: 'center',
      shadowColor: theme.primary,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.1,
      shadowRadius: 12,
      elevation: 2,
    },
    submitText: {
      color: theme.onPrimary,
      fontWeight: '800',
    },
    loadingOverlay: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: 'rgba(0,0,0,0.45)',
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 30,
    },
    modalSafeArea: {
      flex: 1,
      backgroundColor: theme.background,
      paddingHorizontal: 16,
      paddingBottom: 16,
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingTop: 8,
      paddingBottom: 10,
    },
    modalTitle: {
      color: theme.textTitle,
      fontSize: 20,
      fontWeight: '900',
    },
    webviewWrapper: {
      height: 260,
      borderRadius: 14,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: theme.borderSoft,
      backgroundColor: theme.surface,
    },
    webview: {
      flex: 1,
    },
    modalHint: {
      marginTop: 8,
      color: theme.textMuted,
      fontSize: 11,
      fontWeight: '400',
    },
    courtListContainer: {
      marginTop: 14,
      flex: 1,
      backgroundColor: theme.surface,
      borderWidth: 1,
      borderColor: theme.borderSoft,
      borderRadius: 14,
      padding: 12,
    },
    courtListTitle: {
      color: theme.textTitle,
      fontSize: 14,
      fontWeight: '700',
      marginBottom: 8,
    },
    courtRow: {
      paddingVertical: 12,
      paddingHorizontal: 10,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: theme.borderSoft,
      backgroundColor: theme.backgroundAlt,
      marginBottom: 8,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    courtRowSelected: {
      borderColor: theme.primary,
      backgroundColor: theme.primarySoft,
    },
    courtRowText: {
      color: theme.textPrimary,
      fontSize: 16,
      fontWeight: '800',
    },
    courtRowTextSelected: {
      color: theme.textTitle,
      fontWeight: '800',
    },
    courtMetaText: {
      marginTop: 2,
      color: theme.textMuted,
      fontSize: 11,
      fontWeight: '400',
    },
    emptyCourtsState: {
      paddingVertical: 24,
      alignItems: 'center',
    },
    emptyCourtsTitle: {
      color: theme.textTitle,
      fontSize: 15,
      fontWeight: '800',
    },
    emptyCourtsText: {
      marginTop: 4,
      color: theme.textMuted,
      fontSize: 12,
      fontWeight: '500',
    },
  });
