import { StyleSheet } from 'react-native';
import { AppTheme } from '../theme';

export const createHomeStyles = (theme: AppTheme) =>
  StyleSheet.create({
    page: {
      backgroundColor: theme.background,
    },
    heroCard: {
      borderRadius: 22,
      padding: 18,
      backgroundColor: theme.surface,
      borderWidth: 1,
      borderColor: theme.borderSoft,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.06,
      shadowRadius: 12,
      elevation: 3,
    },
    heroTopRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    heroEyebrow: {
      color: theme.primary,
      fontSize: 12,
      fontWeight: '800',
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    livePill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: theme.successSoft,
      borderRadius: 999,
      paddingHorizontal: 10,
      paddingVertical: 6,
    },
    liveDot: {
      width: 6,
      height: 6,
      borderRadius: 999,
      backgroundColor: theme.success,
    },
    liveText: {
      color: theme.textPrimary,
      fontSize: 12,
      fontWeight: '700',
    },
    heroTitle: {
      marginTop: 12,
      color: theme.textTitle,
      fontSize: 28,
      lineHeight: 34,
      fontWeight: '900',
    },
    heroSubtitle: {
      marginTop: 8,
      color: theme.textSubtitle,
      fontSize: 14,
      lineHeight: 21,
      fontWeight: '500',
    },
    statsRow: {
      marginTop: 14,
      flexDirection: 'row',
      gap: 10,
      flexWrap: 'wrap',
    },
    statCard: {
      flexGrow: 1,
      minWidth: 98,
      borderRadius: 14,
      paddingHorizontal: 12,
      paddingVertical: 10,
      backgroundColor: theme.backgroundAlt,
      borderWidth: 1,
      borderColor: theme.borderSoft,
    },
    statValue: {
      color: theme.textTitle,
      fontSize: 17,
      fontWeight: '900',
    },
    statLabel: {
      marginTop: 2,
      color: theme.textMuted,
      fontSize: 11,
      fontWeight: '600',
    },
    actionsRow: {
      marginTop: 14,
      flexDirection: 'row',
      gap: 10,
    },
    actionCard: {
      flex: 1,
      height: 56,
      borderRadius: 12,
      paddingHorizontal: 14,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
    },
    actionPrimary: {
      backgroundColor: theme.primary,
    },
    actionSecondary: {
      backgroundColor: theme.surface,
      borderWidth: 1,
      borderColor: theme.borderSoft,
    },
    actionPrimaryText: {
      color: theme.onPrimary,
      fontWeight: '800',
      fontSize: 14,
    },
    actionSecondaryText: {
      color: theme.primary,
      fontWeight: '800',
      fontSize: 14,
    },
    sectionHeader: {
      marginTop: 20,
      marginBottom: 10,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    sectionTitle: {
      color: theme.textTitle,
      fontSize: 22,
      fontWeight: '900',
    },
    sectionLink: {
      color: theme.primary,
      fontSize: 13,
      fontWeight: '700',
    },
    gridContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 12,
    },
    card: {
      width: '100%',
      borderRadius: 16,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: theme.borderSoft,
    },
    cardBg: {
      width: '100%',
      height: 170,
    },
    cardImage: {
      borderRadius: 16,
    },
    cardOverlay: {
      flex: 1,
      justifyContent: 'space-between',
      padding: 14,
    },
    cardHeaderRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      gap: 10,
    },
    cardTitle: {
      flex: 1,
      color: theme.onPrimary,
      fontSize: 18,
      fontWeight: '900',
      textShadowColor: 'rgba(0,0,0,0.55)',
      textShadowOffset: { width: 0, height: 1 },
      textShadowRadius: 5,
    },
    statusBadge: {
      backgroundColor: 'rgba(255,255,255,0.2)',
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 999,
    },
    statusText: {
      color: theme.onPrimary,
      fontSize: 10,
      fontWeight: '800',
      textTransform: 'uppercase',
      letterSpacing: 0.4,
    },
    cardBottom: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-end',
    },
    cardMeta: {
      color: 'rgba(255,255,255,0.92)',
      fontSize: 12,
      fontWeight: '600',
      marginTop: 2,
    },
    emptyCard: {
      borderRadius: 16,
      borderWidth: 1,
      borderColor: theme.borderSoft,
      backgroundColor: theme.surface,
      padding: 20,
      alignItems: 'center',
      gap: 8,
    },
    emptyTitle: {
      color: theme.textTitle,
      fontSize: 16,
      fontWeight: '800',
    },
    emptySubtitle: {
      color: theme.textMuted,
      fontSize: 13,
      fontWeight: '500',
      textAlign: 'center',
    },
    emptyCta: {
      marginTop: 6,
      backgroundColor: theme.primary,
      borderRadius: 10,
      paddingHorizontal: 14,
      paddingVertical: 10,
    },
    emptyCtaText: {
      color: theme.onPrimary,
      fontSize: 13,
      fontWeight: '800',
    },
  });
