import { Platform, StyleSheet } from 'react-native';
import { AppTheme } from '../../theme';

const createPistaTypesStyles = (theme: AppTheme) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.background,
    },
    scrollContent: {
      paddingHorizontal: 16,
      paddingBottom: 40,
    },
    headerCard: {
      marginTop: 16,
      minHeight: 158,
      borderRadius: 14,
      backgroundColor: theme.primary,
      marginBottom: 20,
      width: '100%',
      overflow: 'hidden',
      ...Platform.select({
        ios: {
          shadowColor: theme.overlayDark,
          shadowOffset: { width: 0, height: 8 },
          shadowOpacity: 0.16,
          shadowRadius: 10,
        },
        android: { elevation: 6 },
      }),
    },
    headerGradient: {
      flex: 1,
      paddingHorizontal: 20,
      paddingVertical: 16,
    },
    headerTopRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      marginBottom: 10,
    },
    headerIconBadge: {
      width: 34,
      height: 34,
      borderRadius: 17,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(255,255,255,0.2)',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.35)',
    },
    headerKicker: {
      color: 'rgba(255,255,255,0.92)',
      fontSize: 12,
      letterSpacing: 0.8,
      fontWeight: '800',
    },
    headerTitle: {
      color: theme.onPrimary,
      fontSize: 28,
      fontWeight: '900',
    },
    headerSubtitle: {
      color: 'rgba(255,255,255,0.92)',
      fontSize: 14,
      marginTop: 4,
      lineHeight: 20,
    },
    headerMetaRow: {
      marginTop: 12,
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    headerMetaChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.35)',
      paddingHorizontal: 10,
      paddingVertical: 6,
      backgroundColor: 'rgba(255,255,255,0.18)',
    },
    headerMetaText: {
      color: theme.onPrimary,
      fontSize: 12,
      fontWeight: '700',
    },
    gridContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 16,
      width: '100%',
    },
    modelCard: {
      height: 250,
      borderRadius: 18,
      overflow: 'hidden',
      backgroundColor: theme.cardBackground,
      borderWidth: 1.2,
      borderColor: 'rgba(255,255,255,0.28)',
      ...Platform.select({
        ios: {
          shadowColor: theme.overlayDark,
          shadowOffset: { width: 0, height: 8 },
          shadowOpacity: 0.26,
          shadowRadius: 9,
        },
        android: { elevation: 8 },
      }),
    },
    dummyCard: {
      flexBasis: 320,
      flexGrow: 1,
      height: 0,
      marginHorizontal: 0,
    },
    modelBg: { flex: 1 },
    modelImageStyle: {
      borderRadius: 16,
      borderColor: '#fff',
      borderWidth: 0.5,
    },
    modelGradient: {
      flex: 1,
      justifyContent: 'space-between',
      padding: 18,
    },
    modelTopRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 8,
    },
    availableBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: 'rgba(255,255,255,0.94)',
      borderRadius: 999,
      paddingHorizontal: 10,
      paddingVertical: 5,
    },
    availableBadgeText: {
      color: theme.textTitle,
      fontWeight: '800',
      fontSize: 11,
    },
    priceTag: {
      backgroundColor: theme.surface,
      paddingHorizontal: 12,
      paddingVertical: 5,
      borderRadius: 20,
    },
    priceTagText: {
      color: theme.primary,
      fontWeight: '800',
      fontSize: 12,
    },
    modelBottomPanel: {
      borderRadius: 14,
      padding: 12,
      backgroundColor: 'rgba(0,0,0,0.24)',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.2)',
    },
    modelBottom: {
      gap: 12,
    },
    modelInfoWrap: {
      gap: 6,
    },
    modelDescription: {
      color: 'rgba(255,255,255,0.92)',
      fontSize: 13,
      lineHeight: 18,
    },
    modelMetaRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    modelMetaChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      borderRadius: 999,
      paddingHorizontal: 9,
      paddingVertical: 5,
      backgroundColor: 'rgba(255,255,255,0.18)',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.28)',
    },
    modelMetaText: {
      color: theme.onPrimary,
      fontSize: 11,
      fontWeight: '700',
    },
    modelCtaPill: {
      flexDirection: 'row',
      alignItems: 'center',
      alignSelf: 'flex-start',
      gap: 6,
      backgroundColor: theme.primary,
      borderRadius: 999,
      paddingHorizontal: 14,
      paddingVertical: 8,
    },
    modelCtaText: {
      color: theme.onPrimary,
      fontWeight: '800',
      fontSize: 12,
    },
    modelTitle: {
      fontWeight: '900',
      fontSize: 25,
      color: theme.onPrimary,
      textShadowColor: theme.overlayDark,
      textShadowOffset: { width: 1, height: 1 },
      textShadowRadius: 4,
    },
    emptyStateCard: {
      marginTop: 8,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.borderSoft,
      backgroundColor: theme.surface,
      alignItems: 'center',
      paddingHorizontal: 20,
      paddingVertical: 22,
      gap: 6,
    },
    emptyStateTitle: {
      color: theme.textTitle,
      fontSize: 16,
      fontWeight: '800',
    },
    emptyStateText: {
      color: theme.textSubtitle,
      fontSize: 13,
      textAlign: 'center',
    },
    loadingContainer: {
      marginTop: 40,
      alignItems: 'center',
      gap: 8,
    },
    loadingText: {
      color: theme.textSubtitle,
      fontSize: 13,
      fontWeight: '600',
    },
  });

export default createPistaTypesStyles;
